model:
  cnn_backbone: mobilenet_v2   # Options: mobilenet_v2, resnet18
  rnn_type: lstm              # Options: lstm, gru
  hidden_size: 256
  num_layers: 1
  num_classes: 2              # Binary classification: real vs fake
  dropout: 0.3

training:
  batch_size: 4
  num_epochs: 20
  learning_rate: 0.0001
  optimizer: adam

data:
  frame_height: 224
  frame_width: 224
  sequence_length: 10         # Number of frames per video sequence
  train_dir: data/processed/train
  val_dir: data/processed/val
